server:
  port: 8088
  undertow:
    accesslog:
      dir: logs
      enabled: true
    threads:
      # 指定工作者线程的 I/0 线程数，默认为 2 或者 CPU 的个数
      io: 8
      # 指定工作者线程个数，默认为 I/O 线程个数的 8 倍
      worker: 256
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理；
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
  #    # 设置 HTTP POST 内容的最大长度，默认不做限制
#    max-http-post-size: 4MB

spring:
  application:
    name: xingyun
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.217.35:31533/xingyun?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 1qaz2wsx
      query.limit: 1000
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        idle-timeout: 30000
  boot:
    admin:
      client:
        url: http://localhost:${server.port}/${spring.boot.admin.context-path}
        instance:
          name: ${spring.application.name}
      context-path: '/monitor'

#  mail:
#    protocol: smtp
#    host: smtp.163.com
#    username: xxxx@163.com
#    password: xxx
#    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# PageHelper插件的配置
pagehelper:
#  helper-dialect: mysql  #指定数据库类型。不配置的话pageHelper也会自动检测
  # 分页合理化参数配置
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true
  # 默认每页条数
  default-page-size: 10
  # 默认第一页
  default-page-num: 1
  params: #默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。



# DFS config  type: hdfs、s3、local
dfs:
  type: hdfs
  namenode.url: hdfs://lake-node3:8020
  namespace: /xingyun
  path.separator: /


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.cloudcharts.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2023-[星云](https://github.com/haibao2015/xingyun)


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
      external-file: /data/app/xingyun/logs/sys-info.log
