server:
  port: 8088

spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.217.35:31533/xingyun?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 1qaz2wsx
      query.limit: 1000
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        idle-timeout: 30000

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# PageHelper插件的配置
pagehelper:
#  helper-dialect: mysql  #指定数据库类型。不配置的话pageHelper也会自动检测
  # 分页合理化参数配置
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true
  # 默认每页条数
  default-page-size: 10
  # 默认第一页
  default-page-num: 1
  params: #默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。



# DFS config  type: hdfs、s3、local
dfs:
  type: hdfs
  namenode.url: hdfs://lake-node3:8020
  namespace: /xingyun
  path.separator: /


knife4j:
  enable: true
  openapi:
    title: 星云官方文档
    description: "`星云`,**666**
    # 888"
    email: swchenminglei@gmail.com
    concat: 无缺
    url: https://github.com/haibao2015/xingyun
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      one:
        group-name: SR-V1
        api-rule: package
        api-rule-resources:
          - com.cloudcharts.controller

#springdoc:
#  swagger-ui:
#    enabled: true
#  api-docs:
#    enabled: true
#    path: /v3/api-docs

