server:
  port: 8088

spring:
  # mysql 配置
  datasource:
    olap:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.217.232:9030/ssb?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password:
      type: com.zaxxer.hikari.HikariDataSource
      query.limit: 1000
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        idle-timeout: 30000
    rdbms:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.217.232:9030/xingyun?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password:
      type: com.zaxxer.hikari.HikariDataSource
      query.limit: 1000
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        idle-timeout: 30000
    logdb:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.217.232:9030/logdb?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password:
      type: com.zaxxer.hikari.HikariDataSource
      query.limit: 1000
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        idle-timeout: 30000
  # mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs







##https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
#olap:
#  type: starrocks
#  driverClassName: com.mysql.cj.jdbc.Driver
#  user: root
#  password:
#  databaseName: ssb
#  portNumber: 9030
#  serverName: 192.168.217.232
#  dataSource:
#    cachePrepStmts: true
#    prepStmtCacheSize: 250
#    prepStmtCacheSqlLimit: 2048
#    useServerPrepStmts: true
#    useLocalSessionState: true
#    rewriteBatchedStatements: true
#    cacheResultSetMetadata: true
#    cacheServerConfiguration: true
#    elideSetAutoCommits: true
#    maintainTimeStats: false
